CC = gcc
CFLAGS = -g -pedantic -Wall -Wextra -pthread -O2 -std=c11
DCFLAGS = -g -pedantic -Wall -Wextra -pthread -O2 -std=c11 -DDEBUG_PRINT

TARGET = main
SRC = main.c

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)

debug: $(SRC)
	$(CC) $(DCFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)

rebuild: clean all

.PHONY: all clean rebuild
