#ifndef DEFAULTS_H__
#define DEFAULTS_H__

#define DEFAULT_MSG_CONFIRM_ARR_SIZE 100
#define DEFAULT_SEEN_MSG_ARR_SIZE 100
#define DEFAULT_UDP_TIMEOUT 250
#define DEFAULT_UDP_RETRANSMISSIONS 3
#define DEFAULT_PORT "4567"
#define DEFAULT_DISPLAY_NAME "unknown"

#endif
